name: Build Website
on:
  schedule:
    - cron: '0 */24 * * *'
  watch:
    types: [started]

jobs:
  build:
    name: Build Website
#    runs-on: ubuntu-18.04
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Checkout avd-repo
        uses: actions/checkout@v2
        with:
          repository: aquasecurity/avd
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: avd-repo

      - name: Check out all other repos
        run: make clone-all

      - name: Build and Generate Markdown pages
        run: make md-generate

      - name: Generate Hugo website
        run: make hugo-generate

      - name: Deploy Search Index to MeiliSearch Instance
        run: |
          cd avd-repo
          curl -H X-Meili-API-Key:\ ${{ secrets.SEARCHAPITOKEN }} -X POST ${{ secrets.SEARCHAPIHOST }}/indexes/content/documents --data @docs/searchindex.json
#        uses: wei/curl@v1
#        with:
#          args: -H X-Meili-API-Key:\ ${{ secrets.SEARCHAPITOKEN }} -X POST ${{ secrets.SEARCHAPIHOST }}/indexes/content/documents --data @docs/searchindex.json

      - name: Commit files to AVD repo
        run: |
          cd avd-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Add changes"
          git push

#      - name: Push changes
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
